# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Area', models.CharField(max_length=100)),
                ('Location_Budget', models.IntegerField()),
                ('Location_City', models.CharField(max_length=100)),
                ('Location_Description', models.CharField(max_length=100)),
                ('Location_District', models.CharField(max_length=100)),
                ('Location_Locality', models.CharField(max_length=100)),
                ('Location_Name', models.CharField(max_length=100)),
                ('Location_Postal_Address', models.CharField(max_length=100)),
                ('Location_Financial', models.CharField(max_length=100)),
                ('Location_Id', models.IntegerField()),
                ('Location_Latitude', models.IntegerField()),
                ('Location_Longitude', models.IntegerField()),
                ('Location_Subcategory', models.CharField(max_length=100)),
                ('Location_Modifications_Allowed', models.CharField(max_length=100)),
                ('Location_Ownership_Status', models.CharField(max_length=100)),
                ('Location_Pincode', models.IntegerField()),
                ('Location_Restrictions', models.CharField(max_length=100)),
                ('Location_State', models.CharField(max_length=100)),
                ('Location_Street_Address', models.CharField(max_length=100)),
                ('Location_Surrounding', models.CharField(max_length=100)),
                ('Location_Modified_Date', models.DateField(auto_now_add=True)),
                ('Location_Created_Date', models.DateField(auto_now_add=True)),
                ('Location_Authorities_Involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationss', to=settings.AUTH_USER_MODEL)),
                ('Location_Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crlocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Location_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
