# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationScheduleForPermit_Comment', models.CharField(max_length=150)),
                ('FilmLocationScheduleForPermit_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmLocationScheduleForPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationScheduleForPermit_Location', models.CharField(max_length=100)),
                ('FilmLocationScheduleForPermit_SNo', models.CharField(max_length=100)),
                ('FilmLocationScheduleForPermit_Modified_Date', models.DateField(auto_now_add=True)),
                ('FilmLocationScheduleForPermit_Created_Date', models.DateField(auto_now_add=True)),
                ('FilmLocationScheduleForPermit_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmlocationscheduleforpermits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_FilmLocationScheduleForPermit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFilmLocationScheduleForPermit', to='FilmLocationScheduleForPermit.FilmLocationScheduleForPermit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='FilmLocationScheduleForPermit_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssFilmLocationScheduleForPermit', to=settings.AUTH_USER_MODEL),
        ),
    ]
