# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conversations_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conversations_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('Conversations_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Conversations_Message_List', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Conversations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_conversations', to='conversations.Conversations'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Conversations_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
