# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dancer_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dancer_Charges_Available', models.BooleanField()),
                ('Dancer_Daily_Charges', models.CharField(max_length=100)),
                ('Dancer_Dancing_Style', models.CharField(max_length=100)),
                ('Dancer_Description', models.CharField(max_length=100)),
                ('Dancer_Genre', models.CharField(max_length=100)),
                ('Dancer_Modified_Date', models.DateField(auto_now_add=True)),
                ('Dancer_Created_Date', models.DateField(auto_now_add=True)),
                ('Dancer_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsDancer', to='Dancers.Dancer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Dancer_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssDancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
