# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationFromGuidedWithSerial_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FilmLocationFromGuidedWithSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationFromGuidedWithSerial_Arrival_Time', models.DateField()),
                ('FilmLocationFromGuidedWithSerial_Departure_Time', models.CharField(max_length=100)),
                ('FilmLocationFromGuidedWithSerial_Location_From_Guideno', models.CharField(max_length=100)),
                ('FilmLocationFromGuidedWithSerial_Location', models.CharField(max_length=100)),
                ('FilmLocationFromGuidedWithSerial_Modified_Date', models.DateField(auto_now_add=True)),
                ('FilmLocationFromGuidedWithSerial_Created_Date', models.DateField(auto_now_add=True)),
                ('FilmLocationFromGuidedWithSerial_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmlocationfromguideds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_FilmLocationFromGuidedWithSerial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFilmLocationFromGuidedWithSerial', to='FilmLocationFromGuidedWithSerial.FilmLocationFromGuidedWithSerial'),
        ),
        migrations.AddField(
            model_name='comment',
            name='FilmLocationFromGuidedWithSerial_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssFilmLocationFromGuidedWithSerial', to=settings.AUTH_USER_MODEL),
        ),
    ]
