# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Rating_Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Rating_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('Rating_Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to=settings.AUTH_USER_MODEL)),
                ('Rating_User_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_Ratings', to='Ratings.Rating'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Rating_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentRatings', to=settings.AUTH_USER_MODEL),
        ),
    ]
