# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Code', models.CharField(max_length=100)),
                ('District_Complete', models.BooleanField()),
                ('District_Name', models.CharField(max_length=100)),
                ('District_Email', models.CharField(max_length=100)),
                ('District_Headquater', models.CharField(max_length=100)),
                ('District_Phq', models.CharField(max_length=100)),
                ('District_Phq_Email', models.CharField(max_length=100)),
                ('District_Phq_Postal_Address', models.CharField(max_length=100)),
                ('District_Phq_Web', models.CharField(max_length=100)),
                ('District_Police_Hqaddress', models.CharField(max_length=100)),
                ('District_Postal_Address', models.CharField(max_length=100)),
                ('District_State', models.CharField(max_length=100)),
                ('District_Web_Address', models.CharField(max_length=100)),
                ('District_Modified_Date', models.DateField(auto_now_add=True)),
                ('District_Created_Date', models.DateField(auto_now_add=True)),
                ('District_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='Districts.District'),
        ),
        migrations.AddField(
            model_name='comment',
            name='District_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
