# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_pitch_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationPitch_Location_Required', models.CharField(max_length=100)),
                ('LocationPitch_Submitted', models.BooleanField(default=False)),
                ('LocationPitch_Modified_Date', models.DateField(auto_now_add=True)),
                ('LocationPitch_Message', models.CharField(max_length=280)),
                ('LocationPitch_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('LocationPitch_By_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pitchs', to=settings.AUTH_USER_MODEL)),
                ('location_pitch_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_location_pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_pitch.LocationPitch'),
        ),
    ]
