# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildArtist_Body_Type', models.TextField(max_length=100)),
                ('ChildArtist_Child_Artist_Id', models.CharField(max_length=100, unique=True)),
                ('ChildArtist_Daily_Charges', models.CharField(max_length=100)),
                ('ChildArtist_Date_Of_Birth', models.DateTimeField(auto_now_add=True)),
                ('ChildArtist_Description', models.CharField(max_length=100)),
                ('ChildArtist_Ethnicity', models.TextField(max_length=100)),
                ('ChildArtist_Eye_Color', models.TextField(max_length=100)),
                ('ChildArtist_Financial_Available', models.BooleanField(default=False)),
                ('ChildArtist_Gender', models.CharField(max_length=100)),
                ('ChildArtist_Height', models.CharField(max_length=100)),
                ('ChildArtist_Relation_With_Artist', models.CharField(max_length=100)),
                ('ChildArtist_Skin_Color', models.TextField(max_length=100)),
                ('ChildArtist_Special_Skills', models.TextField(max_length=100)),
                ('ChildArtist_Weight', models.CharField(max_length=100)),
                ('ChildArtist_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('ChildArtist_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_Artist_Comment', models.CharField(max_length=150)),
                ('Child_Artist_Comment_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childartists', to=settings.AUTH_USER_MODEL)),
                ('Comment_Child_Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='ChildArtist.ChildArtist')),
            ],
        ),
    ]
