# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_subcategory_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationSubCategory_Location_Category', models.CharField(max_length=100)),
                ('Location_Subcategory', models.CharField(max_length=100)),
                ('LocationSubCategory_Subcategory_No', models.CharField(max_length=100)),
                ('LocationSubCategory_Modified_Date', models.DateField(auto_now_add=True)),
                ('LocationSubCategory_Message', models.CharField(max_length=280)),
                ('LocationSubCategory_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('LocationSubCategory_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_subcategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_location_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_subcategory.LocationSubCategory'),
        ),
    ]
