# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationInfo_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationInfo_Course', models.CharField(max_length=100)),
                ('EducationInfo_Course_Detail', models.CharField(max_length=100)),
                ('EducationInfo_Institute', models.CharField(max_length=100)),
                ('EducationInfo_Passing_Year', models.CharField(max_length=100)),
                ('EducationInfo_Modified_Date', models.DateField(auto_now_add=True)),
                ('EducationInfo_Created_Time', models.DateField(auto_now_add=True)),
                ('EducationInfo_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationInfos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_EducationInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsEducationInfo', to='EducationInfos.EducationInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='EducationInfo_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssEducationInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
