# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimicry_artist_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MimicryArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MimicryArtist_Daily_Financials', models.CharField(max_length=200)),
                ('MimicryArtist_Description', models.CharField(max_length=500)),
                ('MimicryArtist_Financials_Available', models.BooleanField()),
                ('MimicryArtist_Voices', models.CharField(max_length=200)),
                ('MimicryArtist_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('MimicryArtist_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_mimicry_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimicry_artist.MimicryArtist'),
        ),
    ]
