# Generated by Django 2.0.3 on 2018-04-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_pdf_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Letter_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_pdf_Addressing_Officer', models.CharField(max_length=100)),
                ('Letter_pdf_Project', models.CharField(max_length=100)),
                ('Letter_pdf_Modified_Date', models.DateField(auto_now_add=True)),
                ('Letter_pdf_Created_Date', models.DateField(auto_now_add=True)),
                ('Letter_pdf_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterpdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Letter_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Letter_pdf.Letter_pdf'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Letter_pdf_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentletterpdf', to=settings.AUTH_USER_MODEL),
        ),
    ]
